### ISSUE TITLE
Expected response code 250 but got code "530"

### ISSUE THREAD

**Issue by wemersonrv** [spatie/nova-backup-tool#66]
Installed and running in a fresh nova installation... but, when i try to create a new backup in `Create  Bckup` button from  nova dashboard, it gives-me the following message in logs:

```bash
**[2019-10-14 20:21:56] local.ERROR: Expected response code 250 but got code "530", with message "530 5.7.1 Authentication required
" {"userId":1,"exception":"[object] (Swift_TransportException(code: 530): Expected response code 250 but got code \"530\", with message \"530 5.7.1 Authentication required
\" at D:\\DadosImportantes\\dev\\Projetos\\WemersonRV\\Laravel\\forex-licenses\\vendor\\swiftmailer\\swiftmailer\\lib\\classes\\Swift\\Transport\\AbstractSmtpTransport.php:457)
[stacktrace]
#0 D:\\DadosImportantes\\dev\\Projetos\\WemersonRV\\Laravel\\forex-licenses\\vendor\\swiftmailer\\swiftmailer\\lib\\classes\\Swift\\Transport\\AbstractSmtpTransport.php(341): Swift_Transport_AbstractSmtpTransport->assertResponseCode('530 5.7.1 Authe...', Array)
#1 D:\\DadosImportantes\\dev\\Projetos\\WemersonRV\\Laravel\\forex-licenses\\vendor\\swiftmailer\\swiftmailer\\lib\\classes\\Swift\\Transport\\EsmtpTransport.php(305): Swift_Transport_AbstractSmtpTransport->executeCommand('MAIL FROM:<hell...', Array, Array, false, NULL)
#2 D:\\DadosImportantes\\dev\\Projetos\\WemersonRV\\Laravel\\forex-licenses\\vendor\\swiftmailer\\swiftmailer\\lib\\classes\\Swift\\Transport\\AbstractSmtpTransport.php(390): Swift_Transport_EsmtpTransport->executeCommand('DATA\
\
', Array, Array)
```

**Comment by freekmurze** [comment]
Seem like your app is trying to send an email.  How does the output of  `config('backup')` look like?

**Comment by freekmurze** [comment]
```
"Spatie\Backup\Notifications\Notifications\BackupHasFailed" => array:1 [
        0 => "mail"
      ]
      "Spatie\Backup\Notifications\Notifications\UnhealthyBackupWasFound" => array:1 [
        0 => "mail"
      ]
      "Spatie\Backup\Notifications\Notifications\CleanupHasFailed" => array:1 [
        0 => "mail"
      ]
      "Spatie\Backup\Notifications\Notifications\BackupWasSuccessful" => array:1 [
        0 => "mail"
      ]
      "Spatie\Backup\Notifications\Notifications\HealthyBackupWasFound" => array:1 [
        0 => "mail"
      ]
      "Spatie\Backup\Notifications\Notifications\CleanupWasSuccessful" => array:1 [
        0 => "mail"
      ]
```

remove those "mail" strings there.

**Comment by wemersonrv** [comment]
> ```
> "Spatie\Backup\Notifications\Notifications\BackupHasFailed" => array:1 [
>         0 => "mail"
>       ]
>       "Spatie\Backup\Notifications\Notifications\UnhealthyBackupWasFound" => array:1 [
>         0 => "mail"
>       ]
>       "Spatie\Backup\Notifications\Notifications\CleanupHasFailed" => array:1 [
>         0 => "mail"
>       ]
>       "Spatie\Backup\Notifications\Notifications\BackupWasSuccessful" => array:1 [
>         0 => "mail"
>       ]
>       "Spatie\Backup\Notifications\Notifications\HealthyBackupWasFound" => array:1 [
>         0 => "mail"
>       ]
>       "Spatie\Backup\Notifications\Notifications\CleanupWasSuccessful" => array:1 [
>         0 => "mail"
>       ]
> ```
> 
> remove those "mail" strings there.

Cool! It works. Tx!
