### ISSUE TITLE
Method translations does not exist

### ISSUE THREAD

**Issue by blaqdog** [spatie/nova-backup-tool#70]
After running

`composer require spatie/nova-backup-tool`

Here is an error
```
  Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

In Nova.php line 706:

  Method translations does not exist.


Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1

```
Full error in Logs
```
[2019-10-29 15:03:37] local.ERROR: Method translations does not exist. {"exception":"[object] (BadMethodCallException(code: 0): Method translations does not exist. at /var/www/html/laravel/nova/src/Nova.php:706)
[stacktrace]
#0 /var/www/html/laravel/vendor/spatie/nova-backup-tool/src/BackupToolServiceProvider.php(68): Laravel\\Nova\\Nova::__callStatic('translations', Array)
#1 /var/www/html/laravel/vendor/spatie/nova-backup-tool/src/BackupToolServiceProvider.php(25): Spatie\\BackupTool\\BackupToolServiceProvider->registerTranslations()
#2 [internal function]: Spatie\\BackupTool\\BackupToolServiceProvider->boot()
#3 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#4 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#5 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#6 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(576): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#7 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(827): Illuminate\\Container\\Container->call(Array)
#8 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(810): Illuminate\\Foundation\\Application->bootProvider(Object(Spatie\\BackupTool\\BackupToolServiceProvider))
#9 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}(Object(Spatie\\BackupTool\\BackupToolServiceProvider), 34)
#10 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(811): array_walk(Array, Object(Closure))
#11 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#12 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(210): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#13 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(162): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#14 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(146): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
#15 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#16 /var/www/html/laravel/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#17 {main}
"} 
```

Have installed 
`composer require spatie/laravel-translatable` and `spatie/laravel-backup`
before

Backups are generating correc with backup:run
How can I fix this error? Thank you

upd: 
laravel 5.8
php 7.2

**Comment by 2sweetworld** [comment]
How did you resolve this?

**Comment by isahlabbo** [comment]
please  this is my problem today can you help me out
